server:
  port: 8081

spring:
  application:
    name: api-proyectos

  kafka:
    bootstrap-servers: kafka:29092
    # Configuración del Productor (Se mantiene para tus updates de Analytics)
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: true

    # 🔥 NUEVO: Configuración del Consumidor para escuchar la limpieza de usuarios
    consumer:
      group-id: proyectos-cleanup-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      auto-offset-reset: earliest

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://db-proyectos:5432/db_proyectos}
    username: ${SPRING_DATASOURCE_USERNAME:admin}
    password: ${SPRING_DATASOURCE_PASSWORD:admin123}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

feign:
  client:
    config:
      default:
        loggerLevel: FULL

# Configuración del Circuit Breaker
resilience4j:
  circuitbreaker:
    instances:
      usuariosCB:
        registerHealthIndicator: true
        slidingWindowSize: 10
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowType: COUNT_BASED
        minimumNumberOfCalls: 5
        waitDurationInOpenState: 5s
        failureRateThreshold: 50
        eventConsumerBufferSize: 10
        writableStackTraceEnabled: true
        shareSecurityContext: true